apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisinsight
  namespace: fcg-infra
  labels:
    app.kubernetes.io/name: redisinsight
    app.kubernetes.io/component: tooling
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redisinsight
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redisinsight
        app.kubernetes.io/component: tooling
    spec:
      containers:
        - name: redisinsight
          image: redislabs/redisinsight:latest
          ports:
            - containerPort: 5540
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: redisinsight-service
  namespace: fcg-infra
  labels:
    app.kubernetes.io/name: redisinsight
    app.kubernetes.io/component: tooling
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: redisinsight
  ports:
    - name: http
      port: 5540
      targetPort: 5540
      nodePort: 30540
