apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kv-fcg-secrets
  namespace: fcg-system
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "00000000-0000-0000-0000-000000000000"
    keyvaultName: "fcg-kv-fiap-2026"
    tenantId: "00000000-0000-0000-0000-000000000000"
    objects: |
      array:
        - |
          objectName: sql-connection-catalog
          objectType: secret
        - |
          objectName: sql-connection-users
          objectType: secret
        - |
          objectName: sql-connection-payments
          objectType: secret
        - |
          objectName: jwt-secret-key
          objectType: secret
        - |
          objectName: redis-connection
          objectType: secret
        - |
          objectName: mongodb-connection
          objectType: secret
        - |
          objectName: elasticsearch-uri
          objectType: secret
        - |
          objectName: eventhub-connection
          objectType: secret
        - |
          objectName: communication-connection
          objectType: secret
  secretObjects:
    - secretName: kv-runtime-secrets
      type: Opaque
      data:
        - objectName: sql-connection-catalog
          key: sql-connection-catalog
        - objectName: sql-connection-users
          key: sql-connection-users
        - objectName: sql-connection-payments
          key: sql-connection-payments
        - objectName: jwt-secret-key
          key: jwt-secret-key
        - objectName: redis-connection
          key: redis-connection
        - objectName: mongodb-connection
          key: mongodb-connection
        - objectName: elasticsearch-uri
          key: elasticsearch-uri
        - objectName: eventhub-connection
          key: eventhub-connection
        - objectName: communication-connection
          key: communication-connection
