apiVersion: v1
kind: Namespace
metadata:
  name: fcg-infra
  labels:
    app.kubernetes.io/part-of: fcg
    environment: local
---
apiVersion: v1
kind: Namespace
metadata:
  name: fcg-users
  labels:
    app.kubernetes.io/part-of: fcg
    environment: local
---
apiVersion: v1
kind: Namespace
metadata:
  name: fcg-payments
  labels:
    app.kubernetes.io/part-of: fcg
    environment: local
---
apiVersion: v1
kind: Namespace
metadata:
  name: fcg-catalog
  labels:
    app.kubernetes.io/part-of: fcg
    environment: local
