kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 16443
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30050
        hostPort: 5050
        protocol: TCP
      - containerPort: 30054
        hostPort: 5054
        protocol: TCP
      - containerPort: 30000
        hostPort: 5000
        protocol: TCP
      - containerPort: 30081
        hostPort: 8081
        protocol: TCP
      - containerPort: 30341
        hostPort: 5341
        protocol: TCP
      - containerPort: 30342
        hostPort: 5342
        protocol: TCP
      - containerPort: 30540
        hostPort: 5540
        protocol: TCP
      - containerPort: 30200
        hostPort: 9200
        protocol: TCP
      - containerPort: 30601
        hostPort: 5601
        protocol: TCP
